dist: bionic
sudo: required

language: cpp
compiler: gcc

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - cmake
            - g++-8
            - gcc-8
           

script:
    - export CC=/usr/bin/gcc-8
    - export CXX=/usr/bin/g++-8
    - export HOMOLOGY_TEST_SOURCES=${TRAVIS_BUILD_DIR}/test
    - gcc -v && g++ -v && cmake --version
    - cmake .
    - make
    - ctest -V
